[workspace]
channels = ["conda-forge", "bioconda"]
name = "gemini-fullstack-langgraph-quickstart"
platforms = ["linux-64"]
version = "0.1.0"

[pypi-options]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"


[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pip = ">=25.1.1,<26"
